"""added landmark and removed constraint for pickup date and pickup time

Revision ID: 8437c66cbf1c
Revises: 90e893507b94
Create Date: 2026-08-02 12:49:07.648384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8437c66cbf1c'
down_revision: Union[str, Sequence[str], None] = '90e893507b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('landmark', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('orders', 'pickup_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('orders', 'pickup_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'pickup_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('orders', 'pickup_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('orders', 'landmark')
    # ### end Alembic commands ###
