"""removed constraint for pickup_address

Revision ID: bc646ac37618
Revises: 9e73ead711bd
Create Date: 2026-08-05 13:38:56.781809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc646ac37618'
down_revision: Union[str, Sequence[str], None] = '9e73ead711bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'pickup_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'pickup_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
